sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
before_install: make clean
before_script:
  - export TEST="1"
script: make test
