sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
before_install: make clean
before_script:
  - export TEST="1"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT